version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - type: bind
        source: ./app
        target: /app
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - api_with_golang-mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_with_golang
volumes:
  api_with_golang-mysql-data: